[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "python -m pip install -r requirements.txt",
  "python -m playwright install chromium",
  "python -m playwright install-deps chromium"
]

[phases.build]
cmds = []

[start]
cmd = "streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"

